### ISSUE TITLE
Bug in `ocplib-config` version 

### ISSUE THREAD

**Issue by cagdasbozman** [OCamlPro/ocp-build#49]
The version given in `ocplib-config` is different from the one in opam:

```
             package: ocplib-config
             version: 1.99.17-beta
          repository: ocaml
            homepage: http://www.typerex.org/ocp-build.html
         bug-reports: https://github.com/OCamlPro/typerex-build/issues
            dev-repo: https://github.com/OCamlPro/typerex-build.git
              author: Fabrice Le Fessant <fabrice.le_fessant@ocamlpro.com>
             depends: typerex-build = 1.99.17-beta
   installed-version: 
   available-version: 1.99.17-beta
         description: A simple library to manage configuration files
```

```
$ ./configure
[...]
checking for OCaml findlib package ocplib-config... 0.1-alpha
[...]
```
